services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:8080'
        volumes:
            - .:/var/www
        networks:
            - default
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
        depends_on:
            - mysql
            - redis

    redis:
       image: redis:latest

    mysql:
        image: 'mariadb:10.3.39'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - default
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
networks:
    default:
        driver: bridge
volumes:
    mysql:
        driver: local
