<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserPerformance extends \App\Doctrine\ORM\Entity\UserPerformance implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'attendance' => [parent::class, 'attendance', null],
        "\0".parent::class."\0".'checksums' => [parent::class, 'checksums', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'generation' => [parent::class, 'generation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'j_card_comment' => [parent::class, 'j_card_comment', null],
        "\0".parent::class."\0".'media_count' => [parent::class, 'media_count', null],
        "\0".parent::class."\0".'media_type' => [parent::class, 'media_type', null],
        "\0".parent::class."\0".'miclocation' => [parent::class, 'miclocation', null],
        "\0".parent::class."\0".'microphones' => [parent::class, 'microphones', null],
        "\0".parent::class."\0".'noise_reduction' => [parent::class, 'noise_reduction', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'performance' => [parent::class, 'performance', null],
        "\0".parent::class."\0".'reference_number' => [parent::class, 'reference_number', null],
        "\0".parent::class."\0".'scms_status' => [parent::class, 'scms_status', null],
        "\0".parent::class."\0".'show_rating' => [parent::class, 'show_rating', null],
        "\0".parent::class."\0".'sound_rating' => [parent::class, 'sound_rating', null],
        "\0".parent::class."\0".'source' => [parent::class, 'source', null],
        "\0".parent::class."\0".'sourceInfo' => [parent::class, 'sourceInfo', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'tapername' => [parent::class, 'tapername', null],
        "\0".parent::class."\0".'tech_note' => [parent::class, 'tech_note', null],
        "\0".parent::class."\0".'traded_from' => [parent::class, 'traded_from', null],
        "\0".parent::class."\0".'traded_from_email' => [parent::class, 'traded_from_email', null],
        "\0".parent::class."\0".'tradesAllowed' => [parent::class, 'tradesAllowed', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'userLists' => [parent::class, 'userLists', null],
        "\0".parent::class."\0".'userid' => [parent::class, 'userid', null],
        'attendance' => [parent::class, 'attendance', null],
        'checksums' => [parent::class, 'checksums', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'generation' => [parent::class, 'generation', null],
        'id' => [parent::class, 'id', null],
        'j_card_comment' => [parent::class, 'j_card_comment', null],
        'media_count' => [parent::class, 'media_count', null],
        'media_type' => [parent::class, 'media_type', null],
        'miclocation' => [parent::class, 'miclocation', null],
        'microphones' => [parent::class, 'microphones', null],
        'noise_reduction' => [parent::class, 'noise_reduction', null],
        'note' => [parent::class, 'note', null],
        'performance' => [parent::class, 'performance', null],
        'reference_number' => [parent::class, 'reference_number', null],
        'scms_status' => [parent::class, 'scms_status', null],
        'show_rating' => [parent::class, 'show_rating', null],
        'sound_rating' => [parent::class, 'sound_rating', null],
        'source' => [parent::class, 'source', null],
        'sourceInfo' => [parent::class, 'sourceInfo', null],
        'status' => [parent::class, 'status', null],
        'tapername' => [parent::class, 'tapername', null],
        'tech_note' => [parent::class, 'tech_note', null],
        'traded_from' => [parent::class, 'traded_from', null],
        'traded_from_email' => [parent::class, 'traded_from_email', null],
        'tradesAllowed' => [parent::class, 'tradesAllowed', null],
        'user' => [parent::class, 'user', null],
        'userLists' => [parent::class, 'userLists', null],
        'userid' => [parent::class, 'userid', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
