<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Doctrine\ORM\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activetrading' => [parent::class, 'activetrading', null],
        "\0".parent::class."\0".'artistGroups' => [parent::class, 'artistGroups', null],
        "\0".parent::class."\0".'artistToArtistGroups' => [parent::class, 'artistToArtistGroups', null],
        "\0".parent::class."\0".'artists' => [parent::class, 'artists', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'columnorder' => [parent::class, 'columnorder', null],
        "\0".parent::class."\0".'config_colors' => [parent::class, 'config_colors', null],
        "\0".parent::class."\0".'config_columns' => [parent::class, 'config_columns', null],
        "\0".parent::class."\0".'config_showrules' => [parent::class, 'config_showrules', null],
        "\0".parent::class."\0".'confirm_hash' => [parent::class, 'confirm_hash', null],
        "\0".parent::class."\0".'cookie_hash' => [parent::class, 'cookie_hash', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'css' => [parent::class, 'css', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'msg_yahoo' => [parent::class, 'msg_yahoo', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'perms' => [parent::class, 'perms', null],
        "\0".parent::class."\0".'picture' => [parent::class, 'picture', null],
        "\0".parent::class."\0".'realemail' => [parent::class, 'realemail', null],
        "\0".parent::class."\0".'rules' => [parent::class, 'rules', null],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null],
        "\0".parent::class."\0".'template' => [parent::class, 'template', null],
        "\0".parent::class."\0".'tradenotes' => [parent::class, 'tradenotes', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'userLists' => [parent::class, 'userLists', null],
        "\0".parent::class."\0".'userPerformances' => [parent::class, 'userPerformances', null],
        "\0".parent::class."\0".'userToArtistGroups' => [parent::class, 'userToArtistGroups', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        "\0".parent::class."\0".'validemail' => [parent::class, 'validemail', null],
        "\0".parent::class."\0".'wantedPerformances' => [parent::class, 'wantedPerformances', null],
        "\0".parent::class."\0".'zipcode' => [parent::class, 'zipcode', null],
        'activetrading' => [parent::class, 'activetrading', null],
        'artistGroups' => [parent::class, 'artistGroups', null],
        'artistToArtistGroups' => [parent::class, 'artistToArtistGroups', null],
        'artists' => [parent::class, 'artists', null],
        'city' => [parent::class, 'city', null],
        'columnorder' => [parent::class, 'columnorder', null],
        'config_colors' => [parent::class, 'config_colors', null],
        'config_columns' => [parent::class, 'config_columns', null],
        'config_showrules' => [parent::class, 'config_showrules', null],
        'confirm_hash' => [parent::class, 'confirm_hash', null],
        'cookie_hash' => [parent::class, 'cookie_hash', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'css' => [parent::class, 'css', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'msg_yahoo' => [parent::class, 'msg_yahoo', null],
        'name' => [parent::class, 'name', null],
        'password' => [parent::class, 'password', null],
        'perms' => [parent::class, 'perms', null],
        'picture' => [parent::class, 'picture', null],
        'realemail' => [parent::class, 'realemail', null],
        'rules' => [parent::class, 'rules', null],
        'state' => [parent::class, 'state', null],
        'template' => [parent::class, 'template', null],
        'tradenotes' => [parent::class, 'tradenotes', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'userLists' => [parent::class, 'userLists', null],
        'userPerformances' => [parent::class, 'userPerformances', null],
        'userToArtistGroups' => [parent::class, 'userToArtistGroups', null],
        'username' => [parent::class, 'username', null],
        'validemail' => [parent::class, 'validemail', null],
        'wantedPerformances' => [parent::class, 'wantedPerformances', null],
        'zipcode' => [parent::class, 'zipcode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
