<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserList extends \App\Doctrine\ORM\Entity\UserList implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'defaultlist' => [parent::class, 'defaultlist', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastviewed' => [parent::class, 'lastviewed', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'private' => [parent::class, 'private', null],
        "\0".parent::class."\0".'ref_username' => [parent::class, 'ref_username', null],
        "\0".parent::class."\0".'shortname' => [parent::class, 'shortname', null],
        "\0".parent::class."\0".'template' => [parent::class, 'template', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'userPerformances' => [parent::class, 'userPerformances', null],
        "\0".parent::class."\0".'views' => [parent::class, 'views', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'defaultlist' => [parent::class, 'defaultlist', null],
        'id' => [parent::class, 'id', null],
        'lastviewed' => [parent::class, 'lastviewed', null],
        'name' => [parent::class, 'name', null],
        'notes' => [parent::class, 'notes', null],
        'private' => [parent::class, 'private', null],
        'ref_username' => [parent::class, 'ref_username', null],
        'shortname' => [parent::class, 'shortname', null],
        'template' => [parent::class, 'template', null],
        'user' => [parent::class, 'user', null],
        'userPerformances' => [parent::class, 'userPerformances', null],
        'views' => [parent::class, 'views', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
