<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity\InternetArchive;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Identifier extends \App\Doctrine\ORM\Entity\InternetArchive\Identifier implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'addedAt' => [parent::class, 'addedAt', null],
        "\0".parent::class."\0".'archiveIdentifier' => [parent::class, 'archiveIdentifier', null],
        "\0".parent::class."\0".'archiveSource' => [parent::class, 'archiveSource', null],
        "\0".parent::class."\0".'collections' => [parent::class, 'collections', null],
        "\0".parent::class."\0".'coverage' => [parent::class, 'coverage', null],
        "\0".parent::class."\0".'creator' => [parent::class, 'creator', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'files' => [parent::class, 'files', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lineage' => [parent::class, 'lineage', null],
        "\0".parent::class."\0".'md5s' => [parent::class, 'md5s', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'performanceDate' => [parent::class, 'performanceDate', null],
        "\0".parent::class."\0".'server' => [parent::class, 'server', null],
        "\0".parent::class."\0".'source' => [parent::class, 'source', null],
        "\0".parent::class."\0".'taper' => [parent::class, 'taper', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'uploader' => [parent::class, 'uploader', null],
        "\0".parent::class."\0".'venue' => [parent::class, 'venue', null],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null],
        'addedAt' => [parent::class, 'addedAt', null],
        'archiveIdentifier' => [parent::class, 'archiveIdentifier', null],
        'archiveSource' => [parent::class, 'archiveSource', null],
        'collections' => [parent::class, 'collections', null],
        'coverage' => [parent::class, 'coverage', null],
        'creator' => [parent::class, 'creator', null],
        'description' => [parent::class, 'description', null],
        'files' => [parent::class, 'files', null],
        'id' => [parent::class, 'id', null],
        'lineage' => [parent::class, 'lineage', null],
        'md5s' => [parent::class, 'md5s', null],
        'notes' => [parent::class, 'notes', null],
        'performanceDate' => [parent::class, 'performanceDate', null],
        'server' => [parent::class, 'server', null],
        'source' => [parent::class, 'source', null],
        'taper' => [parent::class, 'taper', null],
        'title' => [parent::class, 'title', null],
        'uploader' => [parent::class, 'uploader', null],
        'venue' => [parent::class, 'venue', null],
        'year' => [parent::class, 'year', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
