<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Source extends \App\Doctrine\ORM\Entity\Source implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'archiveIdentifier' => [parent::class, 'archiveIdentifier', null],
        "\0".parent::class."\0".'checksums' => [parent::class, 'checksums', null],
        "\0".parent::class."\0".'circdate' => [parent::class, 'circdate', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'dummyColumn' => [parent::class, 'dummyColumn', null],
        "\0".parent::class."\0".'enterUsername' => [parent::class, 'enterUsername', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'identifier' => [parent::class, 'identifier', null],
        "\0".parent::class."\0".'mediaSize' => [parent::class, 'mediaSize', null],
        "\0".parent::class."\0".'mediaSizeUncompressed' => [parent::class, 'mediaSizeUncompressed', null],
        "\0".parent::class."\0".'performance' => [parent::class, 'performance', null],
        "\0".parent::class."\0".'shndiskcount' => [parent::class, 'shndiskcount', null],
        "\0".parent::class."\0".'textdoc' => [parent::class, 'textdoc', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'userPerformances' => [parent::class, 'userPerformances', null],
        "\0".parent::class."\0".'wavdiskcount' => [parent::class, 'wavdiskcount', null],
        'archiveIdentifier' => [parent::class, 'archiveIdentifier', null],
        'checksums' => [parent::class, 'checksums', null],
        'circdate' => [parent::class, 'circdate', null],
        'comments' => [parent::class, 'comments', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'dummyColumn' => [parent::class, 'dummyColumn', null],
        'enterUsername' => [parent::class, 'enterUsername', null],
        'id' => [parent::class, 'id', null],
        'identifier' => [parent::class, 'identifier', null],
        'mediaSize' => [parent::class, 'mediaSize', null],
        'mediaSizeUncompressed' => [parent::class, 'mediaSizeUncompressed', null],
        'performance' => [parent::class, 'performance', null],
        'shndiskcount' => [parent::class, 'shndiskcount', null],
        'textdoc' => [parent::class, 'textdoc', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'userPerformances' => [parent::class, 'userPerformances', null],
        'wavdiskcount' => [parent::class, 'wavdiskcount', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
