<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArtistGroup extends \App\Doctrine\ORM\Entity\ArtistGroup implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'title', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'header', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'footer', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'id', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'artistToArtistGroups', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'userToArtistGroups', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'title', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'header', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'footer', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'id', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'artistToArtistGroups', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'userToArtistGroups', '' . "\0" . 'App\\Doctrine\\ORM\\Entity\\ArtistGroup' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArtistGroup $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTitle($title = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeader($header = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeader', [$header]);

        return parent::setHeader($header);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeader', []);

        return parent::getHeader();
    }

    /**
     * {@inheritDoc}
     */
    public function setFooter($footer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFooter', [$footer]);

        return parent::setFooter($footer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFooter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFooter', []);

        return parent::getFooter();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addArtistToArtistGroup(\App\Doctrine\ORM\Entity\ArtistToArtistGroup $artistToArtistGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArtistToArtistGroup', [$artistToArtistGroup]);

        return parent::addArtistToArtistGroup($artistToArtistGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArtistToArtistGroup(\App\Doctrine\ORM\Entity\ArtistToArtistGroup $artistToArtistGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArtistToArtistGroup', [$artistToArtistGroup]);

        return parent::removeArtistToArtistGroup($artistToArtistGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtistToArtistGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtistToArtistGroups', []);

        return parent::getArtistToArtistGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserToArtistGroup(\App\Doctrine\ORM\Entity\UserToArtistGroup $userToArtistGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserToArtistGroup', [$userToArtistGroup]);

        return parent::addUserToArtistGroup($userToArtistGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserToArtistGroup(\App\Doctrine\ORM\Entity\UserToArtistGroup $userToArtistGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserToArtistGroup', [$userToArtistGroup]);

        return parent::removeUserToArtistGroup($userToArtistGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserToArtistGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserToArtistGroups', []);

        return parent::getUserToArtistGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Doctrine\ORM\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
