<?php

namespace DoctrineProxies\__CG__\App\Doctrine\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArtistGroup extends \App\Doctrine\ORM\Entity\ArtistGroup implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'artistToArtistGroups' => [parent::class, 'artistToArtistGroups', null],
        "\0".parent::class."\0".'footer' => [parent::class, 'footer', null],
        "\0".parent::class."\0".'header' => [parent::class, 'header', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'userToArtistGroups' => [parent::class, 'userToArtistGroups', null],
        'artistToArtistGroups' => [parent::class, 'artistToArtistGroups', null],
        'footer' => [parent::class, 'footer', null],
        'header' => [parent::class, 'header', null],
        'id' => [parent::class, 'id', null],
        'title' => [parent::class, 'title', null],
        'user' => [parent::class, 'user', null],
        'userToArtistGroups' => [parent::class, 'userToArtistGroups', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
